filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
build:
  environment:
    php: '7.4'
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=.coverage.tmp'
        coverage:
          file: '.coverage.tmp'
          format: 'clover'
